### ISSUE TITLE
Duplicate annotations with invalid dates

### ISSUE THREAD

**Issue by mariusandra** [PostHog/github-release-tracking-plugin#2]
@yakkomajuri I set up the annotation tracker to fetch annotations for the project `keajs/kea`. However now it ingests the same 100 annotations every day. 

The plugin server ingestion itself is currently off on cloud (ingesting one event every minute), so these 100 annotation events show up nicely every day at midnight UTC:

![image](https://user-images.githubusercontent.com/53387/108172763-80826c80-70fd-11eb-8c9b-4487b464c301.png)

A lot of the annotations also have "invalid date" as their date.

![image](https://user-images.githubusercontent.com/53387/108172885-af004780-70fd-11eb-85c8-bda8aa173297.png)

---

Also, this script should probably not run at "the next midnight after enabling the plugin", since you'll be left wondering if the plugin even works or not. Instead it should probably use some form of caching ("if (last checked at < 60 minutes) checkAnnotations();") and then check if it needs to fetch the annotations more often, e.g. in `setupPlugin` and in `runEveryHour`...

**Comment by yakkomajuri** [comment]
Yeah I do need to revisit the date on this - I made some updates to the other ones but didn't get back here. 

There's some other rough edges I need to look into, thanks for testing!

Duplicate annotations are new to me though - I've ran this for long periods on our cloud account as well as the playground and never had that problem. Will add a test for it though.

**Comment by yakkomajuri** [comment]
Had some time to look at this now - problem is that we paginate the annotations endpoint and that isn't handled. Fixing.
